package interception

type Filter int

const (
	KEY_DOWN                    Filter = 0x00
	KEY_UP                      Filter = 0x01
	KEY_E0                      Filter = 0x02
	KEY_E1                      Filter = 0x04
	KEY_TERMSRV_SET_LED         Filter = 0x08
	KEY_TERMSRV_SHADOW          Filter = 0x10
	KEY_TERMSRV_VKPACKET        Filter = 0x20
	FILTER_KEY_NONE             Filter = 0x0000
	FILTER_KEY_ALL              Filter = 0xFFFF
	FILTER_KEY_DOWN             Filter = KEY_UP
	FILTER_KEY_UP               Filter = KEY_UP << 1
	FILTER_KEY_E0               Filter = KEY_E0 << 1
	FILTER_KEY_E1               Filter = KEY_E1 << 1
	FILTER_KEY_TERMSRV_SET_LED  Filter = KEY_TERMSRV_SET_LED << 1
	FILTER_KEY_TERMSRV_SHADOW   Filter = KEY_TERMSRV_SHADOW << 1
	FILTER_KEY_TERMSRV_VKPACKET Filter = KEY_TERMSRV_VKPACKET << 1

	MOUSE_LEFT_BUTTON_DOWN   Filter = 0x001
	MOUSE_LEFT_BUTTON_UP     Filter = 0x002
	MOUSE_RIGHT_BUTTON_DOWN  Filter = 0x004
	MOUSE_RIGHT_BUTTON_UP    Filter = 0x008
	MOUSE_MIDDLE_BUTTON_DOWN Filter = 0x010
	MOUSE_MIDDLE_BUTTON_UP   Filter = 0x020

	MOUSE_BUTTON_1_DOWN Filter = MOUSE_LEFT_BUTTON_DOWN
	MOUSE_BUTTON_1_UP   Filter = MOUSE_LEFT_BUTTON_UP
	MOUSE_BUTTON_2_DOWN Filter = MOUSE_RIGHT_BUTTON_DOWN
	MOUSE_BUTTON_2_UP   Filter = MOUSE_RIGHT_BUTTON_UP
	MOUSE_BUTTON_3_DOWN Filter = MOUSE_MIDDLE_BUTTON_DOWN
	MOUSE_BUTTON_3_UP   Filter = MOUSE_MIDDLE_BUTTON_UP

	FILTER_MOUSE_NONE Filter = 0x0000
	FILTER_MOUSE_ALL  Filter = 0xFFFF

	FILTER_MOUSE_LEFT_BUTTON_DOWN   Filter = MOUSE_LEFT_BUTTON_DOWN
	FILTER_MOUSE_LEFT_BUTTON_UP     Filter = MOUSE_LEFT_BUTTON_UP
	FILTER_MOUSE_RIGHT_BUTTON_DOWN  Filter = MOUSE_RIGHT_BUTTON_DOWN
	FILTER_MOUSE_RIGHT_BUTTON_UP    Filter = MOUSE_RIGHT_BUTTON_UP
	FILTER_MOUSE_MIDDLE_BUTTON_DOWN Filter = MOUSE_MIDDLE_BUTTON_DOWN
	FILTER_MOUSE_MIDDLE_BUTTON_UP   Filter = MOUSE_MIDDLE_BUTTON_UP

	FILTER_MOUSE_BUTTON_1_DOWN Filter = MOUSE_BUTTON_1_DOWN
	FILTER_MOUSE_BUTTON_1_UP   Filter = MOUSE_BUTTON_1_UP
	FILTER_MOUSE_BUTTON_2_DOWN Filter = MOUSE_BUTTON_2_DOWN
	FILTER_MOUSE_BUTTON_2_UP   Filter = MOUSE_BUTTON_2_UP
	FILTER_MOUSE_BUTTON_3_DOWN Filter = MOUSE_BUTTON_3_DOWN
	FILTER_MOUSE_BUTTON_3_UP   Filter = MOUSE_BUTTON_3_UP

	FILTER_MOUSE_MOVE Filter = 0x1000
)
